### ISSUE TITLE
[FEATURE REQUEST] Cancel threads from a recursive search.

### ISSUE THREAD

**Issue by islanddog** [epi052/feroxbuster#107]
**Is your feature request related to a problem? Please describe.**
Nope; actually I came across this last week and love it.

**Describe the solution you'd like**
The ability to cut a thread on a scan. So for instance, if I find a hidden CMS solution on a port at `/wordpress/` and the scan begins scanning the `/wordpress/` directory to stop the scan of the original directory. I get I could cancel or start a new instance but with application searching, you could filter your recursive searching to cut down on time. I guess you could also pipe it into an additional scan?

**Describe alternatives you've considered**
Cancelling the current scan and starting a new one.

**Additional context**
None.

**Comment by epi052** [comment]
Thanks for the request!  

The pause|resume feature added in 1.4.0 is a gateway of sorts into features like this. 

The vision was you can pause the scan, and then stop current scans based on some form of input. That's effectively what you're talking about, right? 

1. Pause scan
2. Stop one or more of the scans currently running
3. Resume all scans that weren't stopped in step 2

Is that similar to what you had in mind?

**Comment by islanddog** [comment]
Yes, that is exactly what I had in mind and I updated to 1.4.0 this morning to test exactly that. Right now it's great for recursive searching but to be able to run a scan and get:

```
IP Address
     WordPress
       - wp-content [x]
       - wp-includes [x]
       - etc
```
and then pause the scan to exclude those directories and continue scanning would really optimize the overall process. So in the use case above I know WordPress includes a wp-content and wp-includes directory but I am trying to see if additional folders/files exist without putting it too many requests to the server.

**Comment by epi052** [comment]
Awesome!  That's essentially where I wanted the pause|resume scan thing to eventually go.  Thanks for the feature request and thank you for checking out the tool!

**Comment by epi052** [comment]
tokio 0.3 added [abort](https://docs.rs/tokio/0.3.3/tokio/task/struct.JoinHandle.html#method.abort) to its JoinHandle struct.  I looked at using a few other solutions, but they'd require a pretty significant overhaul to the current structure.

I'd like to wait on the following libraries to upgrade to tokio 0.3 so that feroxbuster can transition to the new version.  Using tokio's built-in abort will drastically simplify this feature.

Upgraded yet?
- [x] hyper 
- [ ] [hyper-tls](https://github.com/hyperium/hyper-tls/issues/76)
- [ ] [reqwest](https://github.com/seanmonstar/reqwest/pull/1076)
- [x] tokio-socks

**Comment by epi052** [comment]
Blockers for this one are all removed, just need to finish up the implementation.  This mainly means figuring out how to get input/output from/to the user in a way that doesn't suck.
