### ISSUE TITLE
Not able to see the icons.

### ISSUE THREAD

**Issue by Strawhack** [epi052/feroxbuster#148]
Hi

First of all thanks for this wonderful tool. Heard from in the community. I installed docker as suggested, with a alias in my zshrc for ease. When i run `feroxbuster` these are the error i am facing
1. I am not able to see the icons. The icons have turned in to question mark as attached in the image.
![ferox](https://user-images.githubusercontent.com/68913486/101131691-b8d0df00-35d3-11eb-8e73-2f16220b49e6.png)
2.  I am not able to mention the word list(the word list exist in the location mentioned on my system) - attached image below
![ferox1](https://user-images.githubusercontent.com/68913486/101131834-efa6f500-35d3-11eb-89d1-bc6ce5f6cdc3.png)

Regards

**Comment by epi052** [comment]
Morning, and thank you for checking out the project!

You're just missing a font that supports emoji.  I updated the Dockerfile to include the noto emoji font.  However, on my system, running from docker appeared to jack up the progress bar printing.  Can you let me know if it shows progress bars on yours or not when using docker? 

For your wordlist issue, it's a similar problem and solution to what is described [for adding a config file](https://github.com/epi052/feroxbuster#mount-a-volume-to-pass-in-ferox-configtoml). The docker version of feroxbuster can't 'see' your dirb wordlist because it exists outside of the container.  

You could consider installing onto your OS using the command below.  It handles installing an emoji font to ~/.fonts and places a copy of feroxbuster in your current working directory.  As this one is on your actual filesystem, it would be able to 'see' dirb's and any other wordlist you'd like to use.  

```bash
curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/master/install-nix.sh | bash
```

**Comment by Strawhack** [comment]
Hi
Thanks a lot. I just installed with above commands. It works perfect. 

Regards
