### ISSUE TITLE
'tokio-runtime-worker' panicked

### ISSUE THREAD

**Issue by saraiva** [epi052/feroxbuster#181]
**Describe the bug**
feroxbuster exits since version 1.11.0 with tokio runtime panick error message

**To Reproduce**
feroxbuster --url URL -o feroxbuster.txt (in this case URL is something in 192.168.*.*)

**Traceback / Error Output**
thread 'tokio-runtime-worker' panicked at 'supplied instant is later than self', library/std/src/time.rs:275:48
stack backtrace:
   0:           0x6f771a - <unknown>
   1:           0x4a61fc - <unknown>
   2:           0x6f6d71 - <unknown>
   3:           0x6f67da - <unknown>
   4:           0x7119fa - <unknown>
   5:           0x7119c4 - <unknown>
   6:           0x71197d - <unknown>
   7:           0x4a3900 - <unknown>
   8:           0x4aa742 - <unknown>
   9:           0x646c63 - <unknown>
  10:           0x62e8b5 - <unknown>
  11:           0x62d94e - <unknown>
  12:           0x6e0259 - <unknown>
  13:           0x43d72d - <unknown>
  14:           0x438cbf - <unknown>
  15:           0x421d4b - <unknown>
  16:           0x72ba20 - <unknown>
  17:           0x7295ad - <unknown>
  18:           0x7288ff - <unknown>
  19:           0x72861b - <unknown>
  20:           0x722915 - <unknown>
zsh: abort      RUST_BACKTRACE=full ../feroxbuster --url URL -o 

**Environment (please complete the following information):**
 - feroxbuster version: 1.11.0
 - Linux kali 5.9.0-kali5-amd64 #1 SMP Debian 5.9.15-1kali1 (2020-12-18) x86_64 GNU/Linux

**Additional context**
The previous version did not panicked on me...

**Comment by epi052** [comment]
Good morning, and thanks for the report!

Judging by `supplied instant is later than self`, my guess is that your system clock is off (are you in a VM?).  

It looks like you removed traceback information.  Could you please find any lines that deal directly with feroxbuster code and let me know which portion of the code is triggering this in your environment? 

Could you please respond back with the information from the following commands? 

```
date
date -u
cat /sys/devices/system/clocksource/clocksource0/current_clocksource
cat /sys/devices/system/clocksource/clocksource0/available_clocksource
grep flags /proc/cpuinfo
cat /proc/cmdline
sudo dmesg | grep -i tsc
```

**Comment by saraiva** [comment]
Hi epi052,
correct, I'm using Kali in a VM.
Strange enough, I didn't remove anything, but the copy/paste didn't work correctly, apparently. But the missing information is not helpful:
   0:           0x6f771a - <unknown>
   1:           0x4a61fc - <unknown>
   2:           0x6f6d71 - <unknown>
   3:           0x6f67da - <unknown>
   4:           0x7119fa - <unknown>
   5:           0x7119c4 - <unknown>
   6:           0x71197d - <unknown>
   7:           0x4a3900 - <unknown>
   8:           0x4aa742 - <unknown>
   9:           0x646c63 - <unknown>
  10:           0x62e8b5 - <unknown>
  11:           0x62d94e - <unknown>
  12:           0x6e0259 - <unknown>
  13:           0x43d72d - <unknown>
  14:           0x438cbf - <unknown>
  15:           0x421d4b - <unknown>
  16:           0x72ba20 - <unknown>
  17:           0x7295ad - <unknown>
  18:           0x7288ff - <unknown>
  19:           0x72861b - <unknown>
  20:           0x722915 - <unknown>

date
Tue 05 Jan 2021 04:32:33 PM CET

date -u
Tue 05 Jan 2021 03:32:50 PM UTC

cat /sys/devices/system/clocksource/clocksource0/current_clocksource
kvm-clock

cat /sys/devices/system/clocksource/clocksource0/available_clocksource
kvm-clock acpi_pm 

grep flags /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni ssse3 pcid sse4_1 sse4_2 hypervisor lahf_lm invpcid_single pti fsgsbase invpcid md_clear flush_l1d arch_capabilities
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni ssse3 pcid sse4_1 sse4_2 hypervisor lahf_lm invpcid_single pti fsgsbase invpcid md_clear flush_l1d arch_capabilities

cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.9.0-kali5-amd64 root=UUID=a6825b63-bb13-4904-a565-b3e60153ab45 ro quiet splash

sudo dmesg | grep -i tsc
[sudo] password for kali: 
[    0.000017] tsc: Detected 2592.000 MHz processor
[    6.388823] clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x255cb6cc5db, max_idle_ns: 440795203504 ns
[    6.555688] TSC synchronization [CPU#0 -> CPU#1]:
[    6.555691] Measured 386374 cycles TSC warp between CPUs, turning off TSC clock.
[    6.555694] tsc: Marking TSC unstable due to check_tsc_sync_source failed

Best regards, Pedro

**Comment by saraiva** [comment]
damnit, again the copy/paste issue :)

0:           0x6f771a - 'unknown'
all memory addresses have a trailing "unknown" string

**Comment by saraiva** [comment]
regarding "Could you please find any lines that deal directly with feroxbuster code and let me know which portion of the code is triggering this in your environment?"
How can I identify those lines? (keep in mind, I'm not a really good developer, quite the opposite :))

**Comment by epi052** [comment]
> regarding "Could you please find any lines that deal directly with feroxbuster code and let me know which portion of the code is triggering this in your environment?"
> How can I identify those lines? (keep in mind, I'm not a really good developer, quite the opposite :))

I was hoping that the traceback included something like 
```
0x800c22ed - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
            at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
```
where the `at /buildslave......` was a source file in feroxbuster (i.e. `src/reporter.rs:351` or similar)

**Comment by epi052** [comment]
@saraiva had a problem where the `Instant::now/elapsed` calls in `logger::initialize` caused a panic on his machine. Dropping his VM down to a single core fixed the problem. The assumption is that his VM cores were out of sync with regard to timing. 

In order to avoid the code in that function, I exposed a `RUST_LOG=off` environment configuration that will skip the timing code tied up in the custom formatter used in logger.rs.  This helped, but tokio appears to use timing for its workers as well, rendering my workaround useless.  

Marking this as wont-fix, as the issue lies with @saraiva's hardware or specific environment.

**Comment by MaximeFrancoeur** [comment]
Tokio thread related -> https://github.com/tokio-rs/tokio/issues/3619

**Comment by davidhacktive** [comment]
@saraiva @epi052 
Just as an FYI (and for others that have been googling this problem):
I've traced back the issue to the Guest Additions and the interactions with the VB host in regards to timing syncing.

So I suspect that any distro will have this issue when VB Guest Additions are installed. With Kali they just have added functionality to detect if it is running in a VM, and then automatically install the guest additions. This will automatically turn on the time syncing with the host. 

This makes it a more apparent problem in Kali+VB due to the above and it's nature being a host for infosec tools.

**The Fix**
Make sure VB is updated, and has the latest Guest Additions installed in Kali. 

```
kali@kali:~$ sudo apt update
...
kali@kali:~$ sudo apt install -y --reinstall virtualbox-guest-x11
...
kali@kali:~$ sudo reboot -f
```

_Reference:
https://www.kali.org/docs/virtualization/install-virtualbox-guest-additions/_

It is more of a a workaround to Guest Additions, but the fix is to disable syncing the time with the host.

This can be done by running the following in a shell:
`VboxManage setextradata <your_vm_name> "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" 1`

(in Windows hosts go to the path of virtual box, usually C:\Program Files\Oracle\VirtualBox\ if you don't have VB added to your $PATH environment variable).

_Reference: (it has the above command)
https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/fine-tune-timers.html_

**Comment by epi052** [comment]
For posterity, the information that @davidhacktive dug up is below. While not a fix, it may be interesting/useful for others.

# :warning: :warning: :warning: does not correct the issue  :warning: :warning: :warning: 
Just as an FYI (and for others that have been googling this problem):
I've traced back the issue to the Guest Additions and the interactions with the VB host in regards to timing syncing.

So I suspect that any distro will have this issue when VB Guest Additions are installed. With Kali they just have added functionality to detect if it is running in a VM, and then automatically install the guest additions. This will automatically turn on the time syncing with the host.

This makes it a more apparent problem in Kali+VB due to the above and it's nature being a host for infosec tools.

The Fix
Make sure VB is updated, and has the latest Guest Additions installed in Kali.

```
kali@kali:~$ sudo apt update
...
kali@kali:~$ sudo apt install -y --reinstall virtualbox-guest-x11
...
kali@kali:~$ sudo reboot -f
```

Reference:
https://www.kali.org/docs/virtualization/install-virtualbox-guest-additions/

It is more of a a workaround to Guest Additions, but the fix is to disable syncing the time with the host.

This can be done by running the following in a shell:
```
VboxManage setextradata <your_vm_name> "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" 1
```
(in Windows hosts go to the path of virtual box, usually `C:\Program Files\Oracle\VirtualBox\` if you don't have VB added to your `$PATH` environment variable).

Reference: (it has the above command)
https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/fine-tune-timers.html

**Comment by epi052** [comment]
Update on this bug. 

As part of the `rustc` 1.60.0 release, this commit was included: https://github.com/rust-lang/rust/commit/9d8ef1160747a4d033f21803770641f2deb32b25

The big takeaway is [listed here](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#instant-monotonicity-guarantees). 

> Incorrectly ordered Instant comparisons no longer panic.

Since [feroxbuster 2.6.3](https://github.com/epi052/feroxbuster/releases/tag/v2.6.3)  was built with `rustc` 1.60.0, my hope is that we shouldn't see this bug crop up anymore from 2.6.3 and up. If you find yourself reading this thread, and still experiencing this bug, please let me know by replying here.

**Comment by 0xm4v3rick** [comment]
Hey @epi052 
Still seeing this issue on ver: 2.7.0. I am using Kali on VirtualBox

`
thread 'tokio-runtime-worker' panicked at 'supplied instant is later than self', library/std/src/time.rs:313:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: done             cat ips.txt | 
zsh: IOT instruction  feroxbuster --stdin -w  -f -k -t 2 --rate-limit 2
`

I tried Guest Additions update as well as 
`
VboxManage setextradata <your_vm_name> "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" 1
`

**Comment by kruug** [comment]
> Hey @epi052 Still seeing this issue on ver: 2.7.0. I am using Kali on VirtualBox
> 

Quit running Kali as a server. That is not what Kali is for.

**Comment by wifiuk** [comment]
i am also getting the same issue, clock time is as expected, have the latest guest additions installed, latest kali version

**Comment by epi052** [comment]
Thank you all for updating this thread. 

I audited feroxbuster's code to make sure I wasn't doing anything specific to trigger this behavior. Fortunately (or unfortunately, depending on your point of view), feroxbuster isn't doing any operations on `Instant`s that would trigger this. 

I checked the compiler used by the github pipeline, and it's of a version high enough that the reported rust-lang fix should be present.

For now, you can try running with `RUST_LOG=off` to see if the logging stuff is at fault.

Additionally, if you can add `RUST_BACKTRACE=1` or `RUST_BACKTRACE=full` to your runs so that we can hopefully capture a bit more information that i can pass on to other places.
