### ISSUE TITLE
[FEATURE REQUEST] Flag to disable DNS error 

### ISSUE THREAD

**Issue by Sicks3c** [epi052/feroxbuster#190]
## Summary

Hello 
Thank you for your amazing tool

I want to ask this feature since when I fuzz I get a lot of DNS issues which makes to output a little difficult to follow through

Like this 
![Check](https://i.imgur.com/UVvAwcl.png)

Best regards

**Comment by epi052** [comment]
Howdy, and thank you for giving it a try! 

The problem here isn't necessarily DNS, but instead a failure to properly join the domain with the word from the wordlist. When a wordlist contains words that begin with 2 forward slashes `//1_40_0/static/js`, the library used for making requests joins the word onto the base url in a surprising way:
```
base_url: https://localhost/ 
word: //1_40_0/static/js
result: https://1_40_0/static/js
```

This is due to the fact that `//...` is a valid url. I've submitted a fix that simply removes prefixed forward slashes if there are two or more of them. v1.12.2 should be ready here in the next 20 minutes or so.  

Thank you for the report!

**Comment by Sicks3c** [comment]
@epi052 

Will it be available in the .deb version I use `feroxbuster` on Ubuntu
Would appreciate it to have it too with the fix

Regards

**Comment by epi052** [comment]
@Sicks3c 

You'll still need to download the latest version of the .deb from https://github.com/epi052/feroxbuster/releases.

The .deb package isn't in any official repos, so it doesn't get updates via apt et al

**Comment by Sicks3c** [comment]
Yes that what I meant I will have to redownload it of course 

Regards
