### ISSUE TITLE
[FEATURE REQUEST] Inform the user when server connections fail due to TLS errors.

### ISSUE THREAD

**Issue by bpsizemore** [epi052/feroxbuster#219]
**Is your feature request related to a problem? Please describe.**
When attempting to connect to HTTPS servers w/o a valid certificate (e.g. self signed when testing internal servers) there is no clear error message other than 
```
Could not connect to https://192.168.0.1, skipping...
```

**Describe the solution you'd like**
Print a unique error message when TLS issues prevent the connection, rather than a timeout or inability to talk to the server
This could look something like
```
Failed to connect to https://192.168.0.1 due to TLS errors, skipping...
```

**Describe alternatives you've considered**
Rather than calling out individual issues, just print a warning after checking all hosts that says something along the lines of
```
Some hosts failed due to TLS errors, run with `-k` to ignore TLS issues and connect to these servers anyways.
```

**Comment by epi052** [comment]
Good morning, 

Thank you for the report! 

For a little backstory, I used to report most things like this as error level messages, but had more than a few folks complain of the noise. With v2.0.0 (pretty sure), i went through and made most (all?) recoverable errors, warnings. At the same time, the overall scan bar displays the number of those recoverable errors you've encountered.  The thought process was that when errors start happening, one could `ctrl+c` the scan, producing a `.state` file, and then run `./feroxbuster --resume-from STATE_FILE.state -v`.  This would pick up their scan from where it left off and add a level of verbosity to see what was going on. I say all that mostly so it's immortalized here and searchable later on :smile:  

Currently, you can see the SSL error when connecting by adding `-v` to your scan command.  However, I agree that this (and similar ssl issues that can be fixed by adding -k) should be shown to the user whether or not they've used `-v`.

**Comment by bpsizemore** [comment]
Thanks for the response and merge! 

Yeah there is definitely a touch balance between noise and usefulness. I was trying out the tool on an internal network yesterday and when I started getting connection errors thought maybe it was due to a janky chain of SSH tunnels and socks proxys being used to hit the internal network. I spent around 15 minutes trying to verify all of those parts before running in verbose mode and realizing the real issue instantly. 😬 

Also thanks for the tip on bumping the version number in the cargo.toml - this was my first contribution to a rust project so my apologies!
