### ISSUE TITLE
[FEATURE REQUEST] Logging to separate files when using --parallel 

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#319]
Thoughts on having an option to log the output of `--parallel` go to a separate file per endpoint?  I imagine it would be in the form of an output directory flag like `--output-directory <name>`

The name of each file wouldn't really matter for my purposes but II suppose it could be consistent with the naming convention for the state files

My use-case is that it's easier to process the files when they're logically separate. I can separate them with Pandas (which is what I use for my post-processing already) it's just a very large file which can cause memory pressure occasionally. It also makes it a bit more of an annoyance to monitor a session while it's still running

The solution/workaround (aside from splitting the data in my post-processing) is using GNU `parallel`. I'm not sure how much (if any) performance impact that has compared with running this all within one instance of feroxbuster. I think that depends on the internals, which I am not too familiar with. I'm not too worried about the overhead associated with the forks since the time relative to the session is pretty small

If you think this isn't too valuable of a feature for most users that use `--parallel`, you don't agree philosophically with the idea, or you don't think there's any advantage to `--parallel` vs GNU `parallel`, feel free to close with a comment

Thanks again for the work you put into this, it's really impressive how far it's come

**Comment by epi052** [comment]
for a historical aside, `--parallel` was initially added because of someone telling me they needed to use `parallel` for large scans. I just wanted to offer a built-in way for that type of usage. 

For what you're asking, it's really a simple addition IF implemented in an opinionated way. Some possible solutions:
- `-o` is assumed to be a directory when `--parallel` is present, and then all files are dumped in there
- value provided to `-o` is ignored and a unique directory is created with the log files (parallel-scan-TIMESTAMP or something)
- something else?  it's late... 

I'm not keen on adding another cli param for this one, as parallel is already a pretty niche thing (you're the second/third person i know of actually using it). I'm leaning toward the first option above and just documenting the difference in `-o` behavior.  What are your thoughts? 

Of note:  I limit verbosity when scanning in parallel.  Logging with --json may be necessary to get the information you want. 

relevant snippet from the readme:
> Unfortunately, using --parallel limits terminal output such that only discovered URLs are shown. No amount of -v's will help you here. I imagine this isn't too big of a deal, as folks that need --parallel probably aren't sitting there watching the output... :upside_down_face:

**Comment by epi052** [comment]
I should have said, I'm spawning children by running `feroxbuster` instances as children from teh main `feroxbuster`.  As such, I have full control over the options/arguments passed to children and could easily change the `-o` value from DIR_NAME to DIR_NAME/UNIQ_FILE_NAME

**Comment by mzpqnxow** [comment]
> I'm not keen on adding another cli param for this one, as parallel is already a pretty niche thing (you're the second/third person i know of actually using it). I'm leaning toward the first option above and just documenting the difference in `-o` behavior. What are your thoughts?
> 

That works for me

> I should have said, I'm spawning children by running feroxbuster instances as children from teh main feroxbuster. As such, I have full control over the options/arguments passed to children and could easily change the -o value from DIR_NAME to DIR_NAME/UNIQ_FILE_NAME

Ah, nice. Well, that works out :>
