### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dhd0004** [epi052/feroxbuster#434]
**Describe the bug**
The program does not stop after executing

**To Reproduce**
1.feroxbuster -w /usr/share/wordlists/seclist/Discovery/Web-Content/common.txt -x jsp,htm,html,do,action --replay-proxy 127.0.0.1:8081 --replay-codes 200,302,401,403 --extract-links -t 20 --time-limit 1h --scan-limit 4 -k -d 2 --url http://zonabeta.movistar.es

**Expected behavior**
Feroxbuster should close after finish

**Traceback / Error Output**
If applicable, add error output to help explain your problem.

**Environment (please complete the following information):**
 - feroxbuster version: 2.4.0
 - OS : Kali Linux 5.4.0-kali2-amd64

**Additional context**
Screenshots
![2021-12-17_13-19](https://user-images.githubusercontent.com/1458162/146543926-467ebf46-84cb-4fcd-9a2f-b891da005f9b.png)
I need to press ctrl+c
![2021-12-17_13-22](https://user-images.githubusercontent.com/1458162/146544176-44659918-0302-4d3d-8227-4b2aa25b06ae.png)

**Comment by epi052** [comment]
Thanks for reporting! I'll see if I can reproduce this behavior over the weekend

**Comment by epi052** [comment]
I'm unable to reproduce what you're seeing. 

The replay proxy side of things **can** take much longer than the scan itself, especially if every request gets replayed due to them all being a 302. 

Can you check to see if your proxy is still logging requests while feroxbuster appears to be hung? Also, just for completeness, are you using the correct proxy port (i see 8081, and burp's default is 8080). Also, is your proxy intercepting and not letting requests through?
