### ISSUE TITLE
[FEATURE REQUEST] add --cookie flag

### ISSUE THREAD

**Issue by unkn0wnsyst3m** [epi052/feroxbuster#442]
I think you forgot to add an option to reuse a cookie?

gobuster dir --url http://192.168.246.147:17445 -x jsp,php,txt,sh -w /usr/share/wordlists/dirb/big.txt -t 40 -c "JSESSIONID=6F792E7FC837806D825C8DC077AF9230"

This option can certainly be done in the "Header" argument field but for ease of use, suggest you give the user a shortcut with a cookie argument

**Comment by epi052** [comment]
Thanks for the suggestion! 

Yea, any cookies right now need to be specified as a Header. Since this is simply a quality of life improvement, I'm going to pin it for now and would happily accept a PR (with guidance/mentoring if needed) for the feature, but I don't plan to personally tackle it at the moment.

Thanks again!

**Comment by 7047payloads** [comment]
I've written some code to implement this feature.

**Comment by epi052** [comment]
@all-contributors add @unkn0wnsyst3m for ideas

**Comment by unkn0wnsyst3m** [comment]
Thanks epi!!  What a guy!

**Comment by epi052** [comment]
@unkn0wnsyst3m and @7047payloads if you've got a twitter account you'd like to me @ when i push 2.5.0, let me know, and thanks again!
