### ISSUE TITLE
[DOCS] add work around for items requiring a comma by using the config file

### ISSUE THREAD

**Issue by vaadata-pascala** [epi052/feroxbuster#653]
**Describe the bug**
I'm working on a project where I need feroxbuster to send a specific header with a value that contains a comma.
Unfortunately, because of the line below, the parameter will be split and the comma will create a new header.

https://github.com/epi052/feroxbuster/blob/bbfaddaedd1b4329a72bca933e44ada6463dafe3/src/parser.rs#L210

**To Reproduce**

```console
$ cargo run -- --url '<myurl>' -H 'Accept: text/html,application/json'
```

**Expected behavior**

Create an header `Accept` with the value `text/html,application/json`

**Traceback / Error Output**

In this case it create an error because it tries to use `application/json` as a header name.

```
thread 'main' panicked at 'Could not rebuild client: invalid HTTP header name', src/config/container.rs:885:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Environment:**
 - feroxbuster version: latest commit (bbfaddaedd1b4329a72bca933e44ada6463dafe3)
 - OS Ubuntu 20.04

**Additional context**

I can't urlencode the comma, this make the header value invalid for the server.

**Comment by epi052** [comment]
Howdy, and thanks for submitting the report!

Can you try putting your header in ferox-config.toml to see if you can pass comma separated values that way?

**Comment by epi052** [comment]
Glad to hear it! So, given that we have a work-around/solution, and because the CLI has behaved this way since it was released, I would prefer not to change it.

Is the config file a suitable solution for your project? 

The config file has some additional functionality talked about [here](https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/) and [here](https://twitter.com/epi052/status/1553383554247262208).

**Comment by epi052** [comment]
sure, we can add a blurb about how to work around items requiring a comma by using the config file :+1:

**Comment by epi052** [comment]
fixed: https://epi052.github.io/feroxbuster-docs/docs/examples/core-features/#include-headers
