### ISSUE TITLE
[FEATURE REQUEST] Chocolatey package

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [epi052/feroxbuster#763]
**Is your feature request related to a problem? Please describe.**
I see many package managers are supported, but on windows it's users are forced to download new binaries manually whenever they want to update feroxbuster :(

**Describe the solution you'd like**
For feroxbuster to get published to chocolatey

**Describe alternatives you've considered**
N/A

**Additional context**
[Chocolatey](https://chocolatey.org/) is a package manager for windows

**Comment by epi052** [comment]
hey there and thanks for submitting this request! I don't plan on prioritizing this over some of the other things I'm working in the ferox realm, but would happily accept a PR for whatever is required to make this happen.

**Comment by aancw** [comment]
I'm working on this feature. Will push whenever the code is ready.

**Comment by aancw** [comment]
Success packaging feroxbuster to chocolatey.
![image](https://user-images.githubusercontent.com/6284204/223140682-f7fdbca5-ac4e-439b-bf44-db6aa4aee3b2.png)

I've created my personal chocolatey account, but i think it's better if the maintainer is epi052 because it's his tool.

After that, @epi052 can push the package to chocolatey using his API credential as explained in this page https://docs.chocolatey.org/en-us/create/create-packages-quick-start

Push the package to the Chocolatey community package repository:

- Get a Chocolatey account:
- [Register](https://chocolatey.org/account/register)
- Copy the API key from [your Chocolatey account](https://chocolatey.org/account).
```
choco apikey --api-key [API_KEY_HERE] -source https://push.chocolatey.org/
choco push package-name.1.1.0.nupkg --source https://push.chocolatey.org/ - nupkg file can be omitted if it is the only one in the directory.
```

**Comment by sitiom** [comment]
On a related note, feroxbuster is now available on [Winget](https://learn.microsoft.com/en-us/windows/package-manager/) 🥳
![image](https://github.com/epi052/feroxbuster/assets/56180050/eaa69896-6520-4b0f-abd1-b78b75cc2e55)

> So, every release of feroxbuster need to be pushed on chocolatey too. I think this can be automated using github workflow.

The same thing applies to Winget. I have opened up a PR for this:
- https://github.com/epi052/feroxbuster/pull/1155

I have opened up a PR for [Scoop](https://scoop.sh/), but it seems not to have been merged yet: https://github.com/ScoopInstaller/Main/pull/5844
