### ISSUE TITLE
builder error: relative URL without a base

### ISSUE THREAD

**Issue by sawmj** [epi052/feroxbuster#977]
**Describe the bug**
I get this error when trying to use some wordlists

`builder error: relative URL without a base`

**To Reproduce**

Simply try using the wordlist of Assetnotes ="httparchive_xml_2023_08_28.txt" OR "httparchive_directories_1m_2023_08_28.txt"

**Comment by epi052** [comment]
poked at this a little bit just now, defo something odd going on, but i think it's with the wordlist (some character/encoding etc)

i'll look at it more a bit later, thanks for reporting!

**Comment by epi052** [comment]
haha, this is a funny one. 

ferox allows you to specify a URL to `--wordlist` in order to download a wordlist over the network, i.e.

```
feroxbuster -u http://localhost -w https://wordlists-cdn.assetnote.io/data/automated/httparchive_xml_2023_08_28.txt
```

since that behavior overloads `--wordlist` we detect if it's a url with a pretty basic check:

```
if wordlist.startswith("http") {
  // download wordlist
}
```

so the wordlists from from assetnote that begin with http make ferox think it's supposed to be downloading from the url `httparchive_xml_2023_08_28.txt`, which is what throws the error.

to resolve the issue, simply rename the wordlist to something that doesn't begin with `http`

**Comment by epi052** [comment]
i added an error message to make what's happening more clear for future users, which will be included in the next release. Thanks again for taking the time to report this!

```
❯ cargo run -- -u http://127.0.0.1:8000 -w httparchive_xml_2023_08_28.txt                                                                                                              
Unable to download wordlist from remote url: httparchive_xml_2023_08_28.txt                                                                                                            
```

**Comment by epi052** [comment]
@all-contributors add @sawmj for bug

**Comment by epi052** [comment]
closing, feel free to reopen if this didn't resolve your issue.
